### ISSUE TITLE
FEATURE: add support for dynamic tags

### ISSUE THREAD

**Issue by LongLiveCHIEF** [HackerHappyHour/tagging-strategy#42]
allow the use of `::true` or `::false` after each tag to specify whether or not that tag should be produced.

This will allow the use of expressions to determine whether or not a tag should be produced.

Example - you may want to produce the X pattern under most conditions, but it doesn't
make sense to do so in the given tag is a pre-release.  You could do something like:

```yaml
-
  name: tagging strategy
  id: tagging-strategy
  with:
    tags: |
      %X%::${{ github.event.action != 'prerelease' }}
      %X.Y.Z%
```
 ﻿
